Update.

diff --git a/.github/workflows/firefox-build.yaml b/.github/workflows/firefox-build.yaml
--- a/.github/workflows/firefox-build.yaml
+++ b/.github/workflows/firefox-build.yaml
@@ -1,4 +1,4 @@
-name: Build Stacer
+name: Build and Release Firefox
 
 on:
   workflow_dispatch:
@@ -17,12 +17,16 @@ jobs:
         run: |
           docker run --rm -v $(pwd):/workspace -w /workspace archlinux:latest bash -c '
             pacman -Syu --noconfirm &&
-            pacman -S --noconfirm sudo base-devel cmake qt6-base qt6-charts qt6-svg qt6-tools git &&
+            pacman -S --noconfirm sudo base-devel alsa-lib at-spi2-core bash cairo dbus ffmpeg \
+              fontconfig freetype2 gcc-libs gdk-pixbuf2 glib2 glibc gtk3 hicolor-icon-theme \
+              libpulse libx11 libxcb libxcomposite libxdamage libxext libxfixes libxrandr \
+              libxss libxt mime-types nspr nss pango ttf-font cbindgen clang diffutils lld \
+              llvm mesa nasm nodejs onnxruntime python rust unzip yasm zip xorg-server-xvfb git &&
             useradd -m builder &&
             chown -R builder:builder /workspace &&
             echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/builder &&
             sudo -u builder bash -c "
-              cd stacer || { echo \"Directory stacer not found\"; exit 1; }
+              cd firefox || { echo \"Directory firefox not found\"; exit 1; }
               makepkg --noconfirm
             "
           '
@@ -34,7 +38,7 @@ jobs:
 
       - name: Extract PKGVER and create Git tag
         run: |
-          pkgver=$(grep "^pkgver=" stacer/PKGBUILD | cut -d= -f2)
+          pkgver=$(grep "^pkgver=" firefox/PKGBUILD | cut -d= -f2)
           echo "PKGVER=$pkgver" >> $GITHUB_ENV
           git config user.name "GitHub Actions"
           git config user.email "actions@github.com"
@@ -45,7 +49,7 @@ jobs:
         uses: softprops/action-gh-release@v2
         with:
           tag_name: v${{ env.PKGVER }}
-          name: Stacer v${{ env.PKGVER }}
-          files: stacer/stacer-1.5.0-2-x86_64.pkg.tar.zst
+          name: Firefox v${{ env.PKGVER }}
+          files: firefox/firefox-144.0-1-x86_64.pkg.tar.zst
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
