Fix.

diff --git a/.github/workflows/onlyoffice-build.yaml b/.github/workflows/onlyoffice-build.yaml
--- a/.github/workflows/onlyoffice-build.yaml
+++ b/.github/workflows/onlyoffice-build.yaml
@@ -1,4 +1,4 @@
-name: Build ONLYOFFICE
+name: Build Stacer
 
 on:
   workflow_dispatch:
@@ -17,13 +17,12 @@ jobs:
         run: |
           docker run --rm -v $(pwd):/workspace -w /workspace archlinux:latest bash -c '
             pacman -Syu --noconfirm &&
-            pacman -S --noconfirm sudo base-devel gtk3 gstreamer gst-plugins-base-libs \
-              libxss nss nspr desktop-file-utils hicolor-icon-theme wget unzip git libarchive &&
+            pacman -S --noconfirm sudo base-devel cmake qt6-base qt6-charts qt6-svg qt6-tools git &&
             useradd -m builder &&
             chown -R builder:builder /workspace &&
             echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/builder &&
             sudo -u builder bash -c "
-              cd onlyoffice || { echo \"Directory onlyoffice not found\"; exit 1; }
+              cd stacer || { echo \"Directory stacer not found\"; exit 1; }
               makepkg --noconfirm
             "
           '
@@ -35,7 +34,7 @@ jobs:
 
       - name: Extract PKGVER and create Git tag
         run: |
-          pkgver=$(grep "^pkgver=" onlyoffice/PKGBUILD | cut -d= -f2)
+          pkgver=$(grep "^pkgver=" stacer/PKGBUILD | cut -d= -f2)
           echo "PKGVER=$pkgver" >> $GITHUB_ENV
           git config user.name "GitHub Actions"
           git config user.email "actions@github.com"
@@ -46,7 +45,7 @@ jobs:
         uses: softprops/action-gh-release@v2
         with:
           tag_name: v${{ env.PKGVER }}
-          name: ONLYOFFICE v${{ env.PKGVER }}
-          files: onlyoffice/onlyoffice-9.1.0-1-x86_64.pkg.tar.zst
+          name: Stacer v${{ env.PKGVER }}
+          files: stacer/stacer-1.5.0-2-x86_64.pkg.tar.zst
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
